export const structs_kdd2019 = {
  "5X8T": {
    kingdom: "e",
    spec: "Chloroplast (Spinacia)",
    res: "3.8 ˚A (EM)",
    pub: "Ahmed et al. (2017)",
  },
  "3J9M": {
    kingdom: "e",
    spec: "Mitochondria (H. Sapiens)",
    res: "3.1 ˚A (EM)",
    pub: "Amunts et al. (2015)",
  },
  "5NJT": {
    spec: "B. subtilis (b)",
    kingdom: "b",
    res: "3.8 ˚A (EM)",
    pub: "Beckert et al. (2017)",
  },
  "5AFI": {
    spec: "E. coli (b)",
    kingdom: "b",
    res: "2.9 ˚A (EM)",
    pub: "Fischer et al. (2015)",
  },
  "5JVG": {
    spec: "D. radiodurans (b)",
    kingdom: "b",
    res: "3.4 ˚A (X-ray)",
    pub: "Krupkin et al. (2016)",
  },
  "5MYJ": {
    spec: "L. lactis (b)",
    kingdom: "b",
    res: "5.6 ˚A (EM)",
    pub: "Franken et al. (2017)",
  },
  "5O60": {
    spec: "M. smegmatis (b)",
    kingdom: "b",
    res: "3.2 ˚A (EM)",
    pub: "Hentschel et al. (2017)",
  },
  "5V7Q": {
    spec: "M. tuberculosis (b)",
    kingdom: "b",
    res: "3.4 ˚A (EM)",
    pub: "Yang et al. (2017)",
  },
  "5NRG": {
    spec: "S. aureus (b)",
    kingdom: "b",
    res: "3.4 ˚A (EM)",
    pub: "Matzov et al. (2017)",
  },
  "4Y4P": {
    spec: "T. thermophilus (b)",
    kingdom: "b",
    res: "2.5 ˚A (EM)",
    pub: "Polinakov et al. (2015)",
  },
  "4V9F": {
    spec: "H. marismortui (a)",
    kingdom: "a",
    res: "2.4 ˚A (X-ray)",
    pub: "Gabdulkhakov et al. (2013)",
  },
  "4V6U": {
    spec: "P. furiosus (a)",
    kingdom: "a",
    res: "6.6 ˚A (EM)",
    pub: "Armache et al. (2012)",
  },
  "6EK0": {
    spec: "H. sapiens (e)",
    kingdom: "e",
    res: "2.9 ˚A (EM)",
    pub: "Natchiar et al. (2017)",
  },
  "5T2A": {
    spec: "L. donovani (e)",
    kingdom: "e",
    res: "2.9 ˚A (EM)",
    pub: "Zhang et al. (2016)",
  },
  "3J79": {
    spec: "P. falciparum (e)",
    kingdom: "e",
    res: "3.2 ˚A (EM)",
    pub: "Wong et al. (2014)",
  },
  "5GAK": {
    spec: "S. cerevisiae (e)",
    kingdom: "e",
    res: "3.9 ˚A (EM)",
    pub: "Schmidt et al. (2016)",
  },
  "4V7E": {
    spec: "T. aestivum (e)",
    kingdom: "e",
    res: "5.5 ˚A (EM)",
    pub: "Gogala et al. (2014)",
  },
  "5T5H": {
    spec: "T. cruzi (e)",
    kingdom: "e",
    res: "2.5 ˚A (EM)",
    pub: "Liu et al. (2016)",
  },
  "5XY3": {
    spec: "T. vaginalis (e)",
    kingdom: "e",
    res: "3.4 ˚A (EM)",
    pub: "Li et al. (2017)",
  },
  "3J7Z": {
    spec: "E. coli (b)",
    kingdom: "b",
    res: "3.9 ˚A (EM)",
    pub: "Arenz et al. (2014)",
  },
  "5VP2": {
    spec: "T. thermophilus (b)",
    kingdom: "b",
    res: "2.8 ˚A (EM)",
    pub: "Osterman et al. (2017)",
  },
  "4UG0": {
    spec: "H. sapiens (e)",
    kingdom: "e",
    res: "3.6 ˚A (EM)",
    pub: "Khatter et al. (2015)",
  },
  "6UZ7": {
    spec: "K. lactis (e)",
    kingdom: "e",
    res: "3.6 ˚A (EM)",
    pub: "Fernandez, I.S., Huang, B.Y.",
  },

  "6HIV": {
    spec: "T. brucei mitochondrion (m)",
    kingdom: "e",
    res: "7.8 ˚A (EM)",
    pub: "Ramrath et al. (2018)",
  },
  "6SPB": {
    spec: "P. aeruginosa (b)",
    kingdom: "b",
    res: "2.82 ˚A (EM)",
    pub: "Halfon et. al (2019)",
  },
  "6V3D": {
    spec: "A. baumanii (b)",
    kingdom: "b",
    res: "2.95 ˚A (EM)",
    pub: "Morgan et al. (2020)",
  },
  "6RXU": {
    spec: "C. thermophilum (e)",
    kingdom: "e",
    res: "3.5 ˚A (EM)",
    pub: "Cheng et al. (2019)",
  },
  "6SGB": {
    spec: "T. brucei brucei (e)",
    kingdom: "e",
    res: "3.30 A",
    pub: "Saurer et al.(2019)",
  },
  "6R6G": {
    spec: "O. cuniculus (e)",
    kingdom: "e",
    res: "3.7",
    pub: "Shanmuganathan et al. (2019)",
  },
};
