---
layout: default
title: Hank Quinlan, Horrible Cop
---

<div class="blurb">
	<h1>Hi there, I'm Ozymandias!</h1>
	<p>I'm best known as a crumbling desert monument  at the end of time.<a href="/about">Read more about my life...</a></p>
</div><!-- /.blurb -->