# Generated by Django 3.0.8 on 2020-07-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbid', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
